spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/billing_discounts}
      auto-index-creation: ${MONGODB_AUTO_INDEX_CREATION:true}
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

discount:
  employee-percentage: ${DISCOUNT_EMPLOYEE_PERCENTAGE:30}
  affiliate-percentage: ${DISCOUNT_AFFILIATE_PERCENTAGE:10}
  loyalty-percentage: ${DISCOUNT_LOYALTY_PERCENTAGE:5}
  bill-threshold: ${DISCOUNT_BILL_THRESHOLD:100}
  bill-discount-amount: ${DISCOUNT_BILL_DISCOUNT_AMOUNT:5}

# Logging Configuration for Development
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    sa.billing.discounts: ${LOGGING_LEVEL_SA_BILLING_DISCOUNTS:DEBUG}
    org.springframework.data.mongodb: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.actuate: INFO
    org.hibernate.validator: WARN
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/billing-discounts-api.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB