spring:
  application:
    name: billing-discounts-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/billing_discounts}
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: ${SPRING_JACKSON_TIME_ZONE:UTC}
    default-property-inclusion: NON_NULL

server:
  port: ${SERVER_PORT:8080}

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,metrics}
  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:always}
  info:
    env:
      enabled: true

# Application Info
app:
  version: ${APP_VERSION:1.0.0}

info:
  app:
    name: Billing Discounts API
    description: RESTful API for calculating retail store discounts
    version: ${app.version}

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
