name: Deploy

on:
  push:
    branches:
      - trunk

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to Cloud Run
        run: ./deploy.sh ${{ secrets.GCP_PROJECT_ID }}
